apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: dtzar/helm-kubectl:3.14
      command:
        - cat
      tty: true