apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: alpine:3.20
      command:
        - cat
      tty: true